version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/examples:/app/examples:ro
      - ./backend/bin:/app/bin:ro
    ports:
      - '5173:5173'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - VITE_API_ROOT=${HOST_API_ROOT:-http://localhost:5173}
    ports:
      - '3000:3000'
    environment:
      - VITE_API_ROOT=${HOST_API_ROOT:-http://localhost:5173}
    depends_on:
      - backend
