!s32i = !cir.int<s, 32>
!u32i = !cir.int<u, 32>
!void = !cir.void
#loc3 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":2:9)
#loc4 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":2:13)
#loc15 = loc(fused[#loc3, #loc4])
!rec___va_list_tag = !cir.record<struct "__va_list_tag" {!u32i, !u32i, !cir.ptr<!void>, !cir.ptr<!void>}>
module @"/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c" attributes {cir.lang = #cir.lang<c>, cir.module_asm = [], cir.record_layouts = {__va_list_tag = #cir.record_layout<arg_passing_kind = can_pass_in_regs, has_trivial_dtor = true, record_align = 8>}, cir.triple = "x86_64-unknown-linux-gnu", dlti.dl_spec = #dlti.dl_spec<!llvm.ptr<270> = dense<32> : vector<4xi64>, !llvm.ptr<271> = dense<32> : vector<4xi64>, !llvm.ptr<272> = dense<64> : vector<4xi64>, i64 = dense<64> : vector<2xi64>, i128 = dense<128> : vector<2xi64>, f80 = dense<128> : vector<2xi64>, !llvm.ptr = dense<64> : vector<4xi64>, i1 = dense<8> : vector<2xi64>, i8 = dense<8> : vector<2xi64>, i16 = dense<16> : vector<2xi64>, i32 = dense<32> : vector<2xi64>, f16 = dense<16> : vector<2xi64>, f64 = dense<64> : vector<2xi64>, f128 = dense<128> : vector<2xi64>, "dlti.endianness" = "little", "dlti.mangling_mode" = "e", "dlti.legal_int_widths" = array<i32: 8, 16, 32, 64>, "dlti.stack_alignment" = 128 : i64>} {
  cir.func no_inline dso_local @sum(%arg0: !s32i {llvm.noundef} loc(fused[#loc3, #loc4]), ...) -> !s32i attributes {nothrow} {
    %0 = cir.alloca !s32i, !cir.ptr<!s32i>, ["count", init] {alignment = 4 : i64} loc(#loc15)
    %1 = cir.alloca !s32i, !cir.ptr<!s32i>, ["__retval"] {alignment = 4 : i64} loc(#loc2)
    %2 = cir.alloca !cir.array<!rec___va_list_tag x 1>, !cir.ptr<!cir.array<!rec___va_list_tag x 1>>, ["ap"] {alignment = 16 : i64} loc(#loc16)
    %3 = cir.alloca !s32i, !cir.ptr<!s32i>, ["x", init] {alignment = 4 : i64} loc(#loc17)
    cir.store %arg0, %0 : !s32i, !cir.ptr<!s32i> loc(#loc9)
    %4 = cir.cast array_to_ptrdecay %2 : !cir.ptr<!cir.array<!rec___va_list_tag x 1>> -> !cir.ptr<!rec___va_list_tag> loc(#loc10)
    cir.va_start %4 : !cir.ptr<!rec___va_list_tag> loc(#loc10)
    %5 = cir.cast array_to_ptrdecay %2 : !cir.ptr<!cir.array<!rec___va_list_tag x 1>> -> !cir.ptr<!rec___va_list_tag> loc(#loc8)
    %6 = cir.va_arg %5 : (!cir.ptr<!rec___va_list_tag>) -> !s32i loc(#loc8)
    cir.store align(4) %6, %3 : !s32i, !cir.ptr<!s32i> loc(#loc17)
    %7 = cir.cast array_to_ptrdecay %2 : !cir.ptr<!cir.array<!rec___va_list_tag x 1>> -> !cir.ptr<!rec___va_list_tag> loc(#loc11)
    cir.va_end %7 : !cir.ptr<!rec___va_list_tag> loc(#loc11)
    %8 = cir.load align(4) %3 : !cir.ptr<!s32i>, !s32i loc(#loc12)
    cir.store %8, %1 : !s32i, !cir.ptr<!s32i> loc(#loc18)
    %9 = cir.load %1 : !cir.ptr<!s32i>, !s32i loc(#loc18)
    cir.return %9 : !s32i loc(#loc18)
  } loc(#loc14)
} loc(#loc)
#loc = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":0:0)
#loc1 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":2:1)
#loc2 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":8:1)
#loc5 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":3:3)
#loc6 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":3:11)
#loc7 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":5:3)
#loc8 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":5:11)
#loc9 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":2:25)
#loc10 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":4:3)
#loc11 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":6:3)
#loc12 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":7:10)
#loc13 = loc("/home/solarowl/Repositories/cir-demo/xcfa-mapper/test/va_start_probe.c":7:3)
#loc14 = loc(fused[#loc1, #loc2])
#loc16 = loc(fused[#loc5, #loc6])
#loc17 = loc(fused[#loc7, #loc8])
#loc18 = loc(fused[#loc13, #loc12])
